# Generated by Django 6.0.4 on 2026-04-19 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('gambar', models.ImageField(upload_to='berita/')),
                ('konten', models.TextField()),
                ('ekosistem', models.CharField(blank=True, choices=[('data_analyst', 'Data Analyst & Visualisasi'), ('saham_crypto', 'Saham & Cryptocurrency'), ('desain_video', 'Desain & Videography'), ('humaniora', 'Humaniora'), ('minat_bakat', 'Minat & Bakat'), ('kewirausahaan', 'Kewirausahaan')], max_length=50, null=True)),
                ('tanggal', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('ekosistem', models.CharField(blank=True, choices=[('data_analyst', 'Data Analyst & Visualisasi'), ('saham_crypto', 'Saham & Cryptocurrency'), ('desain_video', 'Desain & Videography'), ('humaniora', 'Humaniora'), ('minat_bakat', 'Minat & Bakat'), ('kewirausahaan', 'Kewirausahaan')], max_length=50, null=True)),
                ('deskripsi', models.TextField()),
                ('tanggal', models.DateTimeField()),
                ('lokasi', models.CharField(max_length=200)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='kegiatan/')),
                ('mode_seleksi', models.CharField(choices=[('auto', 'Auto Approve'), ('manual', 'Manual Approval')], default='manual', max_length=20)),
                ('brief_deskripsi', models.TextField(blank=True, help_text='Deskripsi tugas untuk peserta')),
                ('brief_link_wa', models.URLField(blank=True, help_text='Link Grup WhatsApp')),
                ('brief_deadline', models.DateTimeField(blank=True, null=True)),
                ('brief_instruksi', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pengurus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('jabatan', models.CharField(max_length=150)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pengurus/')),
                ('periode', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PesanKontak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('pesan', models.TextField()),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dokumentasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ekosistem', models.CharField(blank=True, choices=[('data_analyst', 'Data Analyst & Visualisasi'), ('saham_crypto', 'Saham & Cryptocurrency'), ('desain_video', 'Desain & Videography'), ('humaniora', 'Humaniora'), ('minat_bakat', 'Minat & Bakat'), ('kewirausahaan', 'Kewirausahaan')], max_length=50, null=True)),
                ('foto', models.ImageField(upload_to='dokumentasi/')),
                ('deskripsi', models.CharField(blank=True, max_length=200)),
                ('kegiatan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dokumentasi', to='app.kegiatan')),
            ],
        ),
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('status_kehadiran', models.CharField(choices=[('peserta', 'Peserta'), ('tamu', 'Tamu')], max_length=20)),
                ('waktu', models.DateTimeField(auto_now_add=True)),
                ('kegiatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absensi', to='app.kegiatan')),
            ],
        ),
        migrations.CreateModel(
            name='Peserta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('no_wa', models.CharField(max_length=20)),
                ('status_pendaftar', models.CharField(choices=[('mahasiswa', 'Mahasiswa'), ('umum', 'Umum')], max_length=20)),
                ('link_wa', models.URLField(blank=True, help_text='Link Whatsapp Opsional')),
                ('status_kelolosan', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Diterima'), ('rejected', 'Ditolak')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kegiatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendaftar', to='app.kegiatan')),
            ],
        ),
    ]
