# Generated by Django 6.0.4 on 2026-04-19 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_jabatan_alter_pengurus_jabatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='absensi',
            name='tanda_tangan',
            field=models.TextField(blank=True, help_text='Data Base64 Tanda Tangan', null=True),
        ),
    ]
